spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop;
    username: sa
    driver-class-name: org.h2.Driver
    password:

  jpa:
#    database: h2
#    database-platform: org.hibernate.dialect.H2Dialect

    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#       show_sql은 System.out으로 출력
        show_sql: true
        format_sql: true



logging:
  level:
#    hibernate.sql은 로그로 출력
    org.hibernate.sql: debug
    org.hibernate.orm.jdbc.bind: trace
